= Инструкции, скрипты и оснастки для изготовления печатных плат на DLP 3d принтерах
:1: http://whoby.ru/page/setkaramka
:2: http://whoby.ru/page/pajalnaja-maska
:anaconda: https://www.anaconda.com/products/distribution

Цель: иметь достаточно технологичный способ изготавливать 1- 2- слойные печатные платы в условиях небольшой мастерской.

== Необходимое оборудование и материалы

* Оборудование:
** Ультрафиолетовый DLP/SLA 3D принтер, чем выше разрешение (мельче пиксель) — тем более тонкие дорожки можно засвечивать.
** Пластиковая оснастка (может быть распечатана по частям на том же 3D принтере, но проще использовать FDM принтер).
** Ламинатор (если используется пленочный фоторезист).
** Станок для нанесения УФ паст через трафаретную сетку (см {1}[1], {2}[2] )
** Кюветы для проявки, травления и промывки.
** Кювета для травления.
* Расходные материалы:
** УФ Паяльная Маска
** УФ Фоторзист (можно обойтись только маской)
** Едкий натр
** Кальцинированная сода
** Реактив для травления
*** Лимонная кислота
*** Перекись водорода 12% или выше
*** Поваренная соль


== Подготовка принтера и оснастки

Для DLP принтера необходимо изготовить оснастку, которая позволит повторяемо размещать заготовку в область засветки УФ лучами с рисунками, последовательно: травления, паяльной маски, шелкографии.

3D модели  такой оснастки на языке OpenSCAD находятся в `scad/dlp_printer_fixture.scad`, размеры оснасток — в файле `scad/dlp_printer_fixtures.scad`.

Пример генерации модели для принтера ANYCUBIC PHOTON MONO 4K:

[source, openscad]
----
dlp_printer_fixture(ANYCUBIC_PHOTON_MONO_4K);
----

== Подготовка и обработка экспорта из KiCad

Вместо


=== Скрипты

Для управления окружением Python используется {anaconda}[Anaconda].

Команда для создания окружения и установки зависимостей:
[source, bash]
----
conda env create -f environment.yml
----

Команда для обновления зависимостей уже установленного окружения:
[source, bash]
----
conda env update
----

== Фрезеровка контура и отверстий


== Травление

