= Щелочной травитель для меди
:whoby: http://whoby.ru/page/shhelochnoj-medno-hloridnyj
:markin_1990: http://www.lib.ru/NTL/CHEMISTRY/PR/s_tr_platy.txt_with-big-pictures.html

Для плат с рисунком защищенным полимерным фоторезистом или оловянным металлорезистом

Рецепт из статьи из {markin_1990}[«Химия и Жизнь»], описание приготовления с фотографиями есть так же на сайте {whoby}[whoby.ru].

В промышленном производстве печатных плат чаще всего применяют щелочной раствор солей меди, содержащий 65 — 110 г/л хлорида меди (II), 100 — 150 г/л хлорида аммония, 20 — 30 г/л карбоната аммония, 400 — 500 мл/л 25% раствора аммиака в воде. Температура при травлении 45 — 50 °С.

== Состав

Приготовление щелочного медно-хлоридного раствора травления, реактивы из расчета на 1 литр раствора:

- `CuCl₂•2H₂O` (дигидрат хлорида меди 2) - 80 г.
- `NH₄Cl` (хлорид аммония) - 120 г.
- `NH₄OH` (25%) (аммиак водный 25%) - 450 мл.
- `(NH₄)₂CO₃` (карбонат аммония / аммоний углекислый) - 25 г. или `NH₄HCO₃` (аммоний углекислый кислый) - 25 гр.


== Рецепт

Раствор 1:

. В 150 мл. воды растворяем 80 грамм дигидрата хлорида меди `CuCl₂•2H₂O`
. Добавляем в раствор 25 грамм карбоната аммония `(NH₄)₂CO₃` или `NH₄HCO₃`. Карбонат аммония является буферным веществом, корректирующим pH в щелочную сторону.

Раствор 2:

. В 200 мл. воды добавляем 450 мл. аммиака водного `NH₄OH` (25%)
. Добавляем в раствор 120 грамм хлористого аммония `NH₄Cl`.

Смешиваем растворы 1 и 2 путем вливания первого раствора во второй и доводим объем раствора водой до 1 литра.


== Травление

* Суть травления заключается в обратимой реакции `Сu(NH₃)₄Сl₂ + Сu => 2Сu(NН₃)₂Сl`.
* Рабочая температура 45 — 50 °С.


== Регенерация

Отработанный раствор легко регенерируется при продувании в него воздуха:

`4Cu(NH₃)₂Cl + O₂ + 4NH₄Cl + 4NH₄0H => 4Cu(NH₃)₄Сl₂ + 6Н₂0`

При этом в растворе истощается аммиак и хлорид аммония, которые необходимо добавлять в раствор. Это, в свою очередь будет увеличивать количество раствора.


== Химия

TBD
