= Кислотный травитель для меди
:cucl2_chemistry: http://anytech.narod.ru/etched_cu.htm
:markin_1990: http://www.lib.ru/NTL/CHEMISTRY/PR/s_tr_platy.txt_with-big-pictures.html

Для плат с рисунком, защищенным полимерным фоторезистом

Рецепт считается общеизвестным, различные его модификации есть в {cucl2_chemistry}[интернете], в старых патентах, публиковались в «Химии и Жизни» ({markin_1990}[С.Маркин]).

Раствор прост в приготовлении, поддаётся регенерации, 100 граммам `CuCl₂` эквивалентна смесь 185 г медного купороса `CuS0₄•5H₂0` и 85 г поваренной соли `NaCl`.

== Состав

Приготовление щелочного медно-хлоридного раствора травления, реактивы из расчета на 1 литр раствора:

- `CuCl₂•2H₂O` (дигидрат хлорида меди 2) — 125 г.
- `NH₄Cl` (хлорид аммония) — 145 г. или `NaCl` (хлорид натрия) — 160 г.

== Рецепт

. В 1 л. горячей воды (около 80 °С) растворяем 125 грамм дигидрата хлорида меди `CuCl₂•2H₂O`;
. Добавляем в раствор 145 грамм хлорида аммония `NH₄Cl` или 160 грамм хлорида натрия `NaCl`;
. Сразу после остывания раствор готов к применению.

== Травление

* Суть травления заключается в обратимой реакции `CuCl₂ + Cu => CuCl`.
* Рабочая температура 45 — 50 °С.
* Получающийся хлорид одновалентной меди CuCl нерастворим в воде, поэтому в раствор добавляют, например, хлорид аммония или хлорид натрия, с которыми `CuCl` образует хорошо растворимые соли с не очень устойчивым комплексным анионом `[CuCl₂][-]`.

== Регенерация

Для этого 1/7 часть отработанного раствора сливают в отдельную тару, оставшуюся часть подкисляют концентрированной соляной кислотой (20 — 25 мл/л), добавляют разбавленный 1:6 пергидроль!footnote:disclaimer[Пергидроль водорода — это 30 %-ный раствор пероксида H₂0₂] (110 — 115 мл/л) и перемешивают раствор воздухом (например, с помощью микро компрессора) 20 — 30 минут. При этом происходит реакция:

`2CuCl + H20₂ + 2HCl => 2CuCl₂ + 2H20`

Из отдельной тары можно в дальнейшем восстановить медь, например химическим осаждением или гальваническим способом.

== Химия происходящих процессов

Первоисточник информации о {cucl2_chemistry}[химии процесса]

Суть травления заключается в обратимой реакции
`CuCl₂ + Cu => CuCl`

Hа холоде процесс идет крайне медленно, т.к. `CuCl` достаточно устойчив. Hо при повышении температуры выше 75-80°С процесс резко ускоряется из-за того, что CuCl гидролизуется горячей водой:

`CuCl => CuCl₂ + Cu`

При травлении медной фольги процесс идет активно до некоторого насыщения раствора медной взвесью, после чего наступает равновесие между выделенной медной взвесью и ее растворением. Причем медная взвесь растворяется гораздо эффективнее фольги, и присутствуя во всем объеме тормозит процесс.

Это связано с большей поверхностной энергией, по сравнению с компактной медью. Можно сместить равновесие, удаляя медь - в простейшем случае отстаиванием, но можно и с применением фильтрации и т.д.

Разложению `CuCl` (а следовательно и обогащению `CuCl₂`) способствует присутствие окислителей, которым может быть даже кислород воздуха и в меньшей степени свет. Сильные окислители, например H₂0₂, ускоряют процесс многократно (в его присутствии заготовки ПП травятся за считанные минуты).

При этом образуется `CuCl₂` и нерастворимая основная соль меди - `CuCl(OH)`, выпадающая в виде зеленого осадка. Ксати, при стоянии на воздухе поверхность насыщенных растворов покрывается пленкой состоящей из `CuCl(OH)` и `CuCO3·Cu(OH)₂` - результатом взаимодействия с кислородом и углекислым газом воздуха.

Hа практике это выглядит следующим образом. Если травление меди происходит не часто, то вполне можно обойтись одним раствором, который после травления "отдыхает", выделяя медь в виде ровного осадка (в осадке также присутствует `CuCl`, `CuCl(OH)` и `CuCO3·Cu(OH)₂`).

В зависимости от скорости охлаждения соотношение выпадающей в осадок меди и солей изменяется. Hапример, если резко разбавить упаренный раствор холодной водой, то обнаружим помутнение раствора, который после отстаивания становится светло-зеленым, в случае медленного остывания в осадок бурый — выпадает медь. В данном случае необходимо одно условие — процесс не должен дойти до насыщения. Этого можно достигнуть двумя способами: увеличением объема раствора и удалением меди.

С первым способом все понятно, а под удалением меди понимается либо перевод одновалентновй меди в двухвалентную, либо отфильтровывание металлической взвеси. Если окислять медь кислородом или кислород содержащими окислителями, то мы неизбежно теряем некоторую часть хлорида в виде основных солей. Можно также просто добавить "свежих" хлорид ионов (например добавлением соляной кислоты), таким образом мы смещаем равновесие в сторону CuCl₂.

- `4CuCl + 4HCl + O2 => 4CuCl₂ + 2H₂0`
- `CuCl(OH) + HCl => CuCl₂ + H₂0`
- `CuCO3·Cu(OH)₂ + 4HCl => 2CuCl₂ + H₂0 + CO2`

К счастью соляная кислота не дефицит, а часто просто крайне нежелательный отход, и это пожалуй самый дешевый способ регенерации раствора `CuCl₂`, но есть большой недостаток: при температуре 75-80°С соляная кислота начинает интенсивно испаряться из раствора. При этом и неприятный запах, и сильная коррозия металлических предметов, находящихся рядом, уже через несколько дней.

Выход из этой ситуации — добавлять кислоту только при необходимости маленькими порциями, а еще лучше использовать герметичную емкость. И пару слов об устойчивости маски (защитного слоя): маска должна быть кислотостойка и механически устойчива при температурах 80-100 °C.

Пожалуй это самое экономичное и экологичное травление (если используется регенерация и герметичная аппаратура).
